import { StyleSheet, Dimensions } from "react-native"

const { width } = Dimensions.get("window")

const colors = {
  background: "#FFFFFF",
  card: "#FFFFFF",
  text: "#1F2937",
  subtext: "#888888",
  primary: "#4CAF50",
  alertBg: "#FEE2E2",
  alertText: "#B91C1C",
  wave: "#E8F5E9",
}

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.background,
    padding: 20,
    alignItems: "center",
    justifyContent: "center",
  },
  title: {
    fontSize: 26,
    fontWeight: "bold",
    color: colors.text,
    marginVertical: 20,
    alignSelf: "center",
  },
  boxContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    flexWrap: "wrap",
    marginBottom: 20,
  },
  box: {
    backgroundColor: colors.card,
    borderRadius: 16,
    padding: 16,
    width: "48%",
    marginBottom: 16,
    alignItems: "center",
    elevation: 3,
    shadowColor: "#000",
    shadowOpacity: 0.1,
    shadowOffset: { width: 0, height: 2 },
    shadowRadius: 4,
  },
  boxLabel: {
    fontSize: 14,
    color: colors.subtext,
    marginTop: 8,
  },
  boxValue: {
    fontSize: 20,
    fontWeight: "bold",
    color: colors.primary,
    marginTop: 4,
  },
  chartTitle: {
    fontSize: 18,
    fontWeight: "600",
    color: colors.text,
    marginBottom: 10,
    marginTop: 10,
  },
  chart: {
    borderRadius: 16,
    marginBottom: 40,
  },
  waveContainer: {
    position: "absolute",
    top: -50,
    left: -80,
    width: 400,
    height: 200,
    backgroundColor: colors.wave,
    borderRadius: 200,
    opacity: 5,
    transform: [{ rotate: "20deg" }],
  },
  waveContainerBottom: {
    position: "absolute",
    bottom: -50,
    right: -80,
    width: 400,
    height: 200,
    backgroundColor: colors.wave,
    borderRadius: 200,
    opacity: 5,
    transform: [{ rotate: "-20deg" }],
  },
  infoSection: {
    marginTop: 10,
    backgroundColor: colors.card,
    padding: 16,
    borderRadius: 16,
    elevation: 3,
    shadowColor: "#000",
    shadowOpacity: 0.1,
    shadowOffset: { width: 0, height: 2 },
    shadowRadius: 4,
  },
  infoTitle: {
    fontSize: 16,
    fontWeight: "bold",
    color: colors.primary,
    marginBottom: 8,
  },
  infoItem: {
    fontSize: 14,
    color: colors.text,
    marginBottom: 4,
  },
  gridContainer: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "center",
    alignItems: "center",
    paddingTop: 40,
  },
  gridItem: {
    width: "30%",
    aspectRatio: 1,
    backgroundColor: colors.card,
    borderRadius: 16,
    alignItems: "center",
    justifyContent: "center",
    margin: 10,
    elevation: 3,
    shadowColor: "#000",
    shadowOpacity: 0.1,
    shadowOffset: { width: 0, height: 2 },
    shadowRadius: 4,
  },
  gridLabel: {
    marginTop: 8,
    fontSize: 12,
    color: colors.primary,
    textAlign: "center",
  },
  gridIcon: {
    alignSelf: "center",
    justifyContent: "center",
    textAlign: "center",
  },
})
