import { StyleSheet, Dimensions } from "react-native";

const { width, height } = Dimensions.get("window");

const colors = {
  background: "#FFFFFF",
  primary: "#4CAF50",
  textDark: "#1F2937",
  textLight: "#666666",
  wave1: "#A5D6A7", // verde claro
  wave2: "#81C784", // verde médio
  wave3: "#66BB6A", // verde forte
  buttonShadow: "#388E3C",
};

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.background,
    padding: 20,
    justifyContent: "center",
    alignItems: "center",
  },
  waveLayer1: {
    position: "absolute",
    top: -90,
    left: -110,
    width: 460,
    height: 270,
    backgroundColor: colors.wave1,
    borderRadius: 300,
    opacity: 0.5,
    transform: [{ rotate: "28deg" }],
    shadowColor: colors.primary,
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.3,
    shadowRadius: 12,
  },
  waveLayer2: {
    position: "absolute",
    top: -70,
    left: -80,
    width: 420,
    height: 220,
    backgroundColor: colors.wave2,
    borderRadius: 250,
    opacity: 0.6,
    transform: [{ rotate: "18deg" }],
    shadowColor: colors.primary,
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.3,
    shadowRadius: 10,
  },
  waveLayer3: {
    position: "absolute",
    top: -50,
    left: -50,
    width: 370,
    height: 190,
    backgroundColor: colors.wave3,
    borderRadius: 200,
    opacity: 0.75,
    transform: [{ rotate: "12deg" }],
    shadowColor: colors.primary,
    shadowOffset: { width: 0, height: 5 },
    shadowOpacity: 0.4,
    shadowRadius: 8,
  },
  content: {
    width: "100%",
    alignItems: "center",
    zIndex: 10,
  },
  title: {
    fontSize: 32,
    fontWeight: "bold",
    color: colors.primary,
    marginBottom: 16,
    textShadowColor: 'rgba(0, 0, 0, 0.15)',
    textShadowOffset: { width: 0, height: 4 },
    textShadowRadius: 6,
    textAlign: "center",
  },
  subtitle: {
    fontSize: 18,
    color: colors.textLight,
    textAlign: "center",
    marginBottom: 40,
    paddingHorizontal: 15,
    lineHeight: 26,
  },
  button: {
    backgroundColor: colors.primary,
    paddingVertical: 16,
    paddingHorizontal: 50,
    borderRadius: 35,
    elevation: 5,
    shadowColor: colors.buttonShadow,
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.4,
    shadowRadius: 12,
    marginBottom: 40,
  },
  buttonText: {
    color: "#fff",
    fontSize: 20,
    fontWeight: "700",
  },

  bottomWaveContainer: {
    position: "absolute",
    bottom: 0,
    width: width,
    height: height * 0.25,
    alignItems: "center",
    justifyContent: "flex-end",
    zIndex: 5,
  },
  bottomWave: {
    position: "absolute",
    bottom: 0,
    width: width * 1.2,
    height: height * 0.2,
    backgroundColor: colors.primary,
    borderTopLeftRadius: width * 0.6,
    borderTopRightRadius: width * 0.6,
    transform: [{ scaleX: 1 }],
  },
  acImage: {
    width: width * 0.5,    
    height: height * 0.25 * 0.7, 
    resizeMode: "contain", 
    position: "absolute",
    bottom: height * 0.12,
    zIndex: 10,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.3,
    shadowRadius: 10,
  },
});

